scrape_configs:
- job_name: 'node'
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
    - targets: ["NODE_IP:NODE_PORT"]

- job_name: 'node-exporter'
  static_configs: 
    - targets: ["node-exporter:9100"]
